### ISSUE TITLE
Unused Variables output

### ISSUE THREAD

**Issue by sebastiansajie** [TPRU-demo/pitaxcalc-demo#123]
@martinholmer @codykallen 

When we run the corporate microsim, we get the following output:-

"Your data include the following unused variables that will be ignored:
  INC_SPL_111A_112
  INCOME_OS_RACEHORSE
  TOTAL_TAX_PAYBL_SEC115JC
  AGGREGATE_LIABILTY
  INT_PAYABLE_234A
  GROSS_TAX_PAYABLE
  SURCHARGE_ON_ABOVE_CRORE
  ADVANCE_TAX
  TOTAL_SCTG ..."

@martinholmer I remember you suppressed this output when we were running the PIT app. Could you please tell us what needs to be changed to do the same for the CIT microsim? Thanks.

**Comment by codykallen** [comment]
@sebastiansajie asked out suppressing the list of unused variables. The easiest way to simply suppress it is by including the argument `verbose=False` when initializing a Calculator, as in
```
calc1 = Calculator(policy=pol, records=recs, corprecords=crecs, verbose=False)
```
The reason that we don't have such output from the personal income tax is that the excess variables that wouldn't be used are dropped in `pitaxdata` when preparing `pit.csv`. When preparing the corporate CSVs, I elected not to drop the excess variables because I believed they might be needed for your continuing work on adding the various corporate schedules.

**Comment by martinholmer** [comment]
@sebastiansajie, Does @codykallen's response make sense to you?  His approach sounds sensible to me?

**Comment by sebastiansajie** [comment]
Thanks @codykallen and @martinholmer. It worked.
