### ISSUE TITLE
Regarding issues in calculation of GTI and other variables with new pit.csv file with same parameters

### ISSUE THREAD

**Issue by shekharkhetan** [TPRU-demo/pitaxcalc-demo#64]
@martinholmer @andersonfrailey: 
1. When i am trying to run the app2.py with a bigger sample size, the dump doesn't show the TTI and other tax1/tax2 for almost 2/3rd of the sample. the error in dump file can be seen as: 
`````````````````````````````
![2018-10-05 4](https://user-images.githubusercontent.com/38833762/46534380-93e26380-c8c5-11e8-8c59-eeb06083419d.png)

the error displayed in the command prompt is:

![2018-10-05 1](https://user-images.githubusercontent.com/38833762/46534514-02272600-c8c6-11e8-891c-9a0bfd9b195e.png)
```````````````````````````````````````````````
So please look into it. The size of the sample is 247485 and the calculation is done only for 71147 samples.

**Comment by martinholmer** [comment]
@shekharkhetan,

The screenshot you sent as part of issue #64 says that your problems began on line 82 of the `functions.py` file and the error message says:
```
Runtime warning: invalid value encountered in maximum
  taxinc = np.maximum(0., calc.array('TTI'))
```
Since zero is a valid value, it is obvious that the calculated value of TTI is invalid (that is, not a valid number) for some individual(s) in your new data set.  It could be that there are NULL (or empty) values in your new data set for some of the components of TTI.  Given the (limited) information you've provided, I don't think there is any reason to change the code.   It looks to me like your new data set is faulty.

@indira-tpru @adc2-tpru @keshavchoudhary87 @sebastiansajie

**Comment by shekharkhetan** [comment]
@martinholmer Thanks. Solved the issue.
