### ISSUE TITLE
Distribution Tables

### ISSUE THREAD

**Issue by sebastiansajie** [TPRU-demo/pitaxcalc-demo#65]
@martinholmer 
Could you please tell us if you could customize the code to generate the distribution tables. Thanks.

**Comment by martinholmer** [comment]
@sebastiansajie asked:
> Could you please tell us if you could customize the code to generate the distribution tables. Thanks.

I'd be happy to work on this, but I'm a little reluctant to start on it.  I'm puzzled why one of my other pull requests (namely #62) was closed without any explanation.  I can take rejection, but it's hard to know how to do better in the future if no reason for the rejection is given.

**Comment by shekharkhetan** [comment]
@sebastiansajie SIr the pull request no. #62 was by Martin Holmer.

**Comment by sebastiansajie** [comment]
@martinholmer 
As we had discussed, my comment on the code triggered a rejection of your pull request. Please clarify if replacing 2017 to 2017-2017 would be better than 2017-2018. As you had mentioned, please do what would is necessary to make least changes to the basic U.S. model. In the case of India people are familiar with reporting output as 2017-18 rather than as 2017.

**Comment by martinholmer** [comment]
@sebastiansajie said in issue #65:
> As we had discussed, my comment on the code triggered a rejection of your pull request #62. Please clarify if replacing 2017 to 2017-2017 would be better than 2017-2018. As you had mentioned, please do what would is necessary to make least changes to the basic U.S. model.  In the case of India people are familiar with reporting output as 2017-18 rather than as 2017.

OK, I'll change pull request #62 to make things more consistent with India tax years.
But before I can do that I need you to Reopen #62.   Can you do that?

Also, and this is an important point @sebastiansajie, in order to prepare a pull request that does what you request in issue #65, I will need somebody at TPRU to merge pull requests #58 (after it is enhanced along the lines suggested in the #58 comment), #60, #61, #62 (after it is re-opened and I revise it to be compatible with India's assessment year designation), and #63.

@adc2-tpru @keshavchoudhary87 @indira-tpru

**Comment by martinholmer** [comment]
Pull requests #80 and #85 resolve issue #65.
