### ISSUE TITLE
Question about using alternative input data

### ISSUE THREAD

**Issue by shekharkhetan** [TPRU-demo/pitaxcalc-demo#67]
@martinholmer @sebastiansajie 
I wanted to ask that if we want to work on different data files and donot want it to be merged but keep only as an exercise on our system without having a merge conflict with the master REPO , what should we do other than working on a branch. Thanks

**Comment by andersonfrailey** [comment]
@shekharkhetan are you talking about using different input datasets when running the calculator? If so, the records class is constructed so that you can use any tax unit data and weights as long as the tax unit data uses the variable names as you'll find in `records_variables.json` and each record has a corresponding weight in the weights file. You can specify which files to use when constructing the records class.

As for avoiding merge conflicts, leave the data file you're using untracked in your folder and don't change the hardcoded value for the default dataset in the records class. When you initialize an instance of a records class it'll look something like:

```python
recs = Records(data=file_name, weights=weights_file)
```

Where `file_name` and `weights_file` are the two alternative data and weights files you're using.

**Comment by martinholmer** [comment]
@shekharkhetan,  Did @andersonfrailey's suggestion in issue #67 work for you?

**Comment by shekharkhetan** [comment]
@martinholmer I have used fetch and merge command. so it got updated. But when I see my repo it gives the message that this branch is 3 commits behind master.

**Comment by martinholmer** [comment]
@shekharkhetan said in issue #67:
> I have used fetch and merge command.  so it got updated. 
> But when I see my repo it gives the message that this branch is 3 commits behind master.

I'm sorry but I don't understand what you are describing. 
[Anderson's suggestion](https://github.com/TPRU-demo/pitaxcalc-demo/issues/67#issuecomment-428226307) did not involve doing any `git` commands.

Can you clarify what your are describing?

**Comment by shekharkhetan** [comment]
@martinholmer will follow up with Anderson as he is in New Delhi now.
